apiVersion: v1
data:
  pubkey: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFEQXVZK3JNZTlPNi9BdFdpNzZVZWc5VmpRREtNR3dsYVQrSk1KeHM3N1ZkRnh3ZTR3T1A4YWM2aVkvcTNsRTg2dllBMXNMeThGTzhSZ29zbVA3YjVIaXhsWm10d1I5MDh2U0RIUXJUN0s0ZnY5NHVYVzh0aWlxT2VkYThFL3dtdDZETm9PZzJEZk5pMDJleXJhbSs5bFAwMGlKK3kxRmI5dVJITFdORTNMRUh1Qkp4SkdQTGd6RDRubmQrNXFwdXZISTdMUHU4VzNMbHZCWlM4ak9DYjNxaGNqR2FhZ2w5RW5OMk1nZFg3OUV3c2Y5Y09rd2l4eEUrWGt1WjdqY1hVQ1E1VEZTUit6WVpLUEU2Q1U1dEp2d1RHbEpEcmdtMGg2YmpTbERzR0dhRThrV2tqWkRrTDVmbUhqQ1BvOEFIUllqUkF0cktudGFaN0lzMGN5VC9LMmYgcm9vdEBhcmNoCg==
kind: Secret
metadata:
  name: my-pub-key
  namespace: nginx-frontend
type: Opaque
