apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-frontend
  namespace: nginx-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-frontend
        volumeMounts:
        - mountPath: /run/secrets/pubkey
          name: pubkey-volume
          readOnly: true
          subPath: pubkey
      volumes:
      - name: pubkey-volume
        secret:
          secretName: my-pub-key
