apiVersion: v1
kind: ConfigMap
data:
  traefik.toml: |
    debug = false
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoint.traefik]
      address = ":8080"
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]
    [api]
    dashboard = true
    entryPoint = "traefik"
    debug = true
    [acme]
    email = "mateo.burillo@sysdig.com"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    [acme.httpChallenge]
    entryPoint = "http"
    [[acme.domains]]
    main = "traefik.sysdig-demo.zone"
metadata:
  name: traefik-conf
  namespace: traefik

