apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-frontend
  namespace: nginx-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-frontend
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
      restartPolicy: Always
      volumes:
      - configMap:
          items:
          - key: nginx-conf
            path: nginx.conf
          name: nginx-conf-name
        name: nginx-config
